### ISSUE TITLE
Mistake in README.md (headers should be object!)

### ISSUE THREAD

**Issue by r007** [elkwood/openai-rtk-client#11]
Hi there,

I noticed that you have a line in example section:

```typescript
store.dispatch(apiSlice.actions.setHeaders('Authorization', `Bearer ${user_token_from_somewhere}`))
```
But the type of payload is ```Record<string, string>```, so that it should be

```typescript
store.dispatch(apiSlice.actions.setHeaders({'Authorization': `Bearer ${user_token_from_somewhere}`}))
```

Hope this helps.

**Comment by elkwood** [comment]
Thanks for bringing this to my attention. I've also regenerated the client to the latest schema in #13 for reference
